name: Release

on:
  push:
    tags:
    - "v*.*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v6
    - name: Install dependencies
      run: sudo apt-get install -y fontforge-nox
    - name: Install TeX Live
      uses: zauguin/install-texlive@v4
      with:
        package_file: .github/tl_packages
    - name: Run make
      run: make fonts
    - name: Build
      run: l3build ctan
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: ccicons-ctan.zip
